# action.yml
name: kyverno-cli-installer
author: kyverno
description: Installs kyverno CLI and includes it in your path
branding:
  icon: package
  color: orange
# This is pinned to the last major release, we have to bump it for each action version.
inputs:
  release:
    description: kyverno CLI release version to be installed
    required: false
    default: v2.1.1
  install-dir:
    description: Where to install the kyverno CLI binary
    required: false
    default: $HOME/.kyverno
  use-sudo:
    description: set to true if install-dir location requires sudo privs
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    # We verify the version against a SHA **in the published action itself**, not in the GCS bucket.
    - shell: bash
      run: |
        #!/bin/bash

        shopt -s expand_aliases

        if [ -z "$NO_COLOR" ]; then
          alias log_info="echo -e \"\033[1;32mINFO\033[0m:\""
          alias log_error="echo -e \"\033[1;31mERROR\033[0m:\""
        else
          alias log_info="echo \"INFO:\""
          alias log_error="echo \"ERROR:\""
        fi

        set -e

        mkdir -p ${{ inputs.install-dir }}

        # main
        if [[ ${{ inputs.release }} == "main" ]]; then
          log_info "installing via 'go install' from its main version"
          GOBIN=$(go env GOPATH)/bin
          go install github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno@main
          ln -s $GOBIN/kubectl-kyverno ${{ inputs.install-dir}}/kubectl-kyverno
          exit 0
        fi
