name: test-action

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install Kyverno CLI and test presence in path
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Kyverno CLI
        uses: ./
      - name: Check install
        run: kyverno version
      - name: Check root directory
        shell: bash
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi

  custom:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install Kyverno CLI and test presence in path
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Kyverno CLI
        uses: ./
        with:
          release: 'v1.9.5'
      - name: Check install
        run: kyverno version
      - name: Check root directory
        shell: bash
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi

  wrong_version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Try to install a wrong version
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Kyverno CLI
        uses: ./
        with:
          release: honk
        continue-on-error: true

  custom_dir:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions: {}
    name: Install Kyverno CLI and test presence in path
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Kyverno CLI
        uses: ./
        with:
          install-dir: "$HOME/.kyvernotest"
      - name: Check install
        run: kyverno version
      - name: Check install dir
        shell: bash
        run: |
          [[ $(dirname "$(which kyverno)") == "$HOME/.kyvernotest" ]]
      - name: Check root directory
        shell: bash
        run: |
          [[ -z $(git diff --stat) ]]

  custom_dir_root:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions: {}
    name: Install Kyverno CLI and test presence in path with custom root dir
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Kyverno CLI
        uses: ./
        with:
          install-dir: /usr/bin
          use-sudo: true
      - name: Check install
        run: kyverno version
      - name: Check install dir
        shell: bash
        run: |
          [[ $(dirname "$(which kyverno)") == /usr/bin ]]
      - name: Check root directory
        shell: bash
        run: |
          [[ -z $(git diff --stat) ]]

  main:
    permissions: {}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        go_version:
          - '1.20'
          - '1.21'
    name: Try to install with go ${{ matrix.go_version }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
      - name: Install Kyverno CLI
        uses: ./
        with:
          release: main
      - name: Check install
        run: kyverno version
